window.translations = {
    "es": {
        "page_title": "Consultora de Inteligencia Artificial",
        "brand_name": "IA Consultores",
        "nav_home": "Inicio",
        "nav_services": "Servicios",
        "nav_about": "Nosotros",
        "nav_contact": "Contacto",
        "nav_login": "Iniciar Sesión",
        "lang_button": "Español",
        "hero_title": "Adelanta tu Empresa al Futuro",
        "hero_subtitle": "Integramos la próxima generación de inteligencia artificial en tu flujo de trabajo para darte una ventaja competitiva decisiva.",
        "hero_button": "Solicita una Consulta",
        "services_title": "Nuestros Servicios",
        "service1_title": "Prototipado Rápido con IA",
        "service1_text": "Validamos tus ideas de negocio en días, no meses, creando prototipos funcionales con herramientas de IA de vanguardia.",
        "service2_title": "Automatización de Procesos",
        "service2_text": "Identificamos cuellos de botella en tu flujo de trabajo y desplegamos soluciones de IA para automatizar tareas repetitivas.",
        "service3_title": "Consultoría Estratégica",
        "service3_text": "Te guiamos en la creación de una hoja de ruta de IA, asegurando que cada inversión tecnológica impulse tus objetivos de negocio.",
        "about_title": "Sobre Nosotros",
        "about_text1": "Somos un equipo de expertos apasionados por la inteligencia artificial y su potencial para resolver problemas complejos. Nuestra misión es ayudar a las empresas a navegar por el paisaje de la IA, identificando oportunidades y desarrollando soluciones innovadoras que generen un impacto real.",
        "about_text2": "Con años de experiencia en la industria, combinamos conocimiento técnico profundo con una comprensión estratégica del negocio para entregar resultados excepcionales.",
        "cta_title": "¿Listo para transformar tu negocio?",
        "cta_subtitle": "Da el siguiente paso hacia la innovación y la eficiencia.",
        "cta_button": "Contacta con un experto",
        "contact_title": "Contáctanos",
        "contact_subtitle": "Estamos listos para ayudarte. Contáctanos para una consulta gratuita.",
        "footer_copyright": "&copy; 2025 IA Consultores. Todos los derechos reservados.",
        "modal_title": "Formulario de Contacto",
        "modal_name_placeholder": "Tu Nombre",
        "modal_email_placeholder": "Tu Correo Electrónico",
        "modal_phone_placeholder": "Número de Celular",
        "modal_message_placeholder": "Mensaje",
        "modal_submit_email_button": "Enviar por Correo",
        "modal_submit_whatsapp_button": "Enviar por WhatsApp",
        "validation_required": "Este campo es obligatorio.",
        "validation_email_invalid": "Por favor, introduce un correo válido.",
        "modal_info_note": "Nota: Los campos marcados con * son obligatorios. El correo electrónico es requerido para envío por email, y el número de celular para envío por WhatsApp.",
        "service_placeholder": "Selecciona un servicio de interés",
        "service_prototyping": "Prototipado Rápido con IA",
        "service_automation": "Automatización de Procesos",
        "service_consulting": "Consultoría Estratégica",
        "service_other": "Otro servicio",
        "login_page_title": "Portal de Clientes - Login",
        "login_welcome": "Bienvenido de Vuelta",
        "login_instruction": "Ingresa tus credenciales para acceder a tu portal.",
        "login_google": "Continuar con Google",
        "login_or": "O",
        "login_email_label": "Correo Electrónico",
        "login_password_label": "Contraseña",
        "login_button": "Ingresar",
        "login_forgot_password": "¿Olvidaste tu contraseña?"
    },
    "en": {
        "page_title": "Artificial Intelligence Consultancy",
        "brand_name": "AI Consultants",
        "nav_home": "Home",
        "nav_services": "Services",
        "nav_about": "About Us",
        "nav_contact": "Contact",
        "nav_login": "Log In",
        "lang_button": "English",
        "hero_title": "Advance Your Company to the Future",
        "hero_subtitle": "We integrate the next generation of artificial intelligence into your workflow to give you a decisive competitive advantage.",
        "hero_button": "Request a Consultation",
        "services_title": "Our Services",
        "service1_title": "Rapid Prototyping with AI",
        "service1_text": "We validate your business ideas in days, not months, creating functional prototypes with cutting-edge AI tools.",
        "service2_title": "Process Automation",
        "service2_text": "We identify bottlenecks in your workflow and deploy AI solutions to automate repetitive tasks.",
        "service3_title": "Strategic Consulting",
        "service3_text": "We guide you in creating an AI roadmap, ensuring that every technological investment drives your business goals.",
        "about_title": "About Us",
        "about_text1": "We are a team of experts passionate about artificial intelligence and its potential to solve complex problems. Our mission is to help companies navigate the AI landscape, identifying opportunities and developing innovative solutions that generate real impact.",
        "about_text2": "With years of industry experience, we combine deep technical knowledge with a strategic understanding of business to deliver exceptional results.",
        "cta_title": "Ready to transform your business?",
        "cta_subtitle": "Take the next step towards innovation and efficiency.",
        "cta_button": "Contact an expert",
        "contact_title": "Contact Us",
        "contact_subtitle": "We are ready to help you. Contact us for a free consultation.",
        "footer_copyright": "&copy; 2025 AI Consultants. All rights reserved.",
        "modal_title": "Contact Form",
        "modal_name_placeholder": "Your Name",
        "modal_email_placeholder": "Your Email",
        "modal_phone_placeholder": "Phone Number",
        "modal_message_placeholder": "Message",
        "modal_submit_email_button": "Send by Email",
        "modal_submit_whatsapp_button": "Send by WhatsApp",
        "validation_required": "This field is required.",
        "validation_email_invalid": "Please enter a valid email address.",
        "modal_info_note": "Note: Fields marked with * are required. Email is required for email delivery, and phone number for WhatsApp delivery.",
        "service_placeholder": "Select a service of interest",
        "service_prototyping": "Rapid Prototyping with AI",
        "service_automation": "Process Automation",
        "service_consulting": "Strategic Consulting",
        "service_other": "Other service",
        "login_page_title": "Client Portal - Login",
        "login_welcome": "Welcome Back",
        "login_instruction": "Enter your credentials to access your portal.",
        "login_google": "Continue with Google",
        "login_or": "OR",
        "login_email_label": "Email Address",
        "login_password_label": "Password",
        "login_button": "Sign In",
        "login_forgot_password": "Forgot your password?"
    },
    "pt": {
        "page_title": "Consultoria de Inteligência Artificial",
        "brand_name": "IA Consultores",
        "nav_home": "Início",
        "nav_services": "Serviços",
        "nav_about": "Sobre Nós",
        "nav_contact": "Contato",
        "nav_login": "Entrar",
        "lang_button": "Português",
        "hero_title": "Leve sua Empresa para o Futuro",
        "hero_subtitle": "Integramos a próxima geração de inteligência artificial em seu fluxo de trabalho para lhe dar uma vantagem competitiva decisiva.",
        "hero_button": "Solicite uma Consulta",
        "services_title": "Nossos Serviços",
        "service1_title": "Prototipagem Rápida com IA",
        "service1_text": "Validamos suas ideias de negócio em dias, não meses, criando protótipos funcionais com ferramentas de IA de ponta.",
        "service2_title": "Automação de Processos",
        "service2_text": "Identificamos gargalos em seu fluxo de trabalho e implantamos soluções de IA para automatizar tarefas repetitivas.",
        "service3_title": "Consultoria Estratégica",
        "service3_text": "Nós o guiamos na criação de um roteiro de IA, garantindo que cada investimento tecnológico impulsione seus objetivos de negócios.",
        "about_title": "Sobre Nós",
        "about_text1": "Somos uma equipe de especialistas apaixonados por inteligência artificial e seu potencial para resolver problemas complexos. Nossa missão é ajudar as empresas a navegar pela paisagem da IA, identificando oportunidades e desenvolvendo soluções inovadoras que gerem impacto real.",
        "about_text2": "Com anos de experiência no setor, combinamos profundo conhecimento técnico com uma compreensão estratégica dos negócios para entregar resultados excepcionais.",
        "cta_title": "Pronto para transformar seu negócio?",
        "cta_subtitle": "Dê o próximo passo em direção à inovação e eficiência.",
        "cta_button": "Fale com um especialista",
        "contact_title": "Fale Conosco",
        "contact_subtitle": "Estamos prontos para ajudá-lo. Fale conosco para uma consulta gratuita.",
        "footer_copyright": "&copy; 2025 IA Consultores. Todos os direitos reservados.",
        "modal_title": "Formulário de Contato",
        "modal_name_placeholder": "Seu Nome",
        "modal_email_placeholder": "Seu E-mail",
        "modal_phone_placeholder": "Seu Número de Celular",
        "modal_message_placeholder": "Mensagem",
        "modal_submit_email_button": "Enviar por E-mail",
        "modal_submit_whatsapp_button": "Enviar por WhatsApp",
        "validation_required": "Este campo é obrigatório.",
        "validation_email_invalid": "Por favor, insira um endereço de e-mail válido.",
        "modal_info_note": "Nota: Os campos marcados com * são obrigatórios. O e-mail é necessário para o envio por e-mail, e o número de celular para o envio por WhatsApp.",
        "service_placeholder": "Selecione um serviço de interesse",
        "service_prototyping": "Prototipagem Rápida com IA",
        "service_automation": "Automação de Processos",
        "service_consulting": "Consultoria Estratégica",
        "service_other": "Outro serviço",
        "login_page_title": "Portal do Cliente - Login",
        "login_welcome": "Bem-vindo de Volta",
        "login_instruction": "Digite suas credenciais para acessar seu portal.",
        "login_google": "Continuar com o Google",
        "login_or": "OU",
        "login_email_label": "Endereço de E-mail",
        "login_password_label": "Senha",
        "login_button": "Entrar",
        "login_forgot_password": "Esqueceu sua senha?"
    }
};

// Confirmar que las traducciones se han cargado
console.log('=== LANGUAGES.JS LOADED SUCCESSFULLY ===');
console.log('window.translations available:', !!window.translations);
console.log('Available languages:', Object.keys(window.translations));